language: python
matrix:
  include:
  - python: '3.7'
    env: TOX_ENV=flake8,mypy,py37,pre-commit
    dist: xenial
    sudo: true # required workaround for https://github.com/travis-ci/travis-ci/issues/9815
  - python: '3.6'
    env: TOX_ENV=py36
cache:
  directories:
  - $HOME/.cache/pip
  - $TRAVIS_BUILD_DIR/.tox
install:
- pip install tox codecov
script:
- tox -e $TOX_ENV -- --cov-report term-missing --cov=graphql_server
after_success:
- codecov
deploy:
  provider: pypi
  user: syrusakbary
  on:
    tags: true
